### ISSUE TITLE
Something introduced a LoRA merging bug

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/litgpt#1224]
Steps to reproduce:

```bash
litgpt download --repo_id EleutherAI/pythia-160m 

litgpt finetune lora --checkpoint_dir checkpoints/EleutherAI/pythia-160m --train.max_steps 5 
```

```
{'checkpoint_dir': PosixPath('checkpoints/EleutherAI/pythia-160m'),
 'data': None,
 'devices': 1,
 'eval': EvalArgs(interval=100, max_new_tokens=100, max_iters=100),
 'logger_name': 'csv',
 'lora_alpha': 16,
 'lora_dropout': 0.05,
 'lora_head': False,
 'lora_key': False,
 'lora_mlp': False,
 'lora_projection': False,
 'lora_query': True,
 'lora_r': 8,
 'lora_value': True,
 'out_dir': PosixPath('out/finetune/lora'),
 'precision': None,
 'quantize': None,
 'seed': 1337,
 'train': TrainArgs(save_interval=1000,
                    log_interval=1,
                    global_batch_size=128,
                    micro_batch_size=4,
                    lr_warmup_steps=100,
                    epochs=5,
                    max_tokens=None,
                    max_steps=5,
                    max_seq_length=None,
                    tie_embeddings=None,
                    learning_rate=0.0003,
                    weight_decay=0.02,
                    beta1=0.9,
                    beta2=0.95,
                    max_norm=None,
                    min_lr=6e-05)}
Using bfloat16 Automatic Mixed Precision (AMP)
Seed set to 1337
Number of trainable parameters: 294,912
Number of non-trainable parameters: 162,322,944
The longest sequence length in the train data is 1035, the model's maximum sequence length is 1035 and context length is 2048
Validating ...
Recommend a movie for me to watch during the weekend and explain the reason.
Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
Recommend a movie for me to watch during the weekend and explain the reason.

### Response:
1. A specific question could return 13 responses.

### Response for Recommence your inquiry

The following instructions help you to answer this question.

### the number of minutes that the memory will be required to complete the task

The number of minutes that the memory ability will be required to complete the task is two times the number of seconds that is required to process the task on each day, or one hundred times the number of seconds that is required to complete the task each
Epoch 1 | iter 1 step 0 | loss train: 3.660, val: n/a | iter time: 189.55 ms
Epoch 1 | iter 2 step 0 | loss train: 3.477, val: n/a | iter time: 47.98 ms
Epoch 1 | iter 3 step 0 | loss train: 3.486, val: n/a | iter time: 69.66 ms
Epoch 1 | iter 4 step 0 | loss train: 3.579, val: n/a | iter time: 45.24 ms
Epoch 1 | iter 5 step 0 | loss train: 3.557, val: n/a | iter time: 45.01 ms
Epoch 1 | iter 6 step 0 | loss train: 3.591, val: n/a | iter time: 44.42 ms
Epoch 1 | iter 7 step 0 | loss train: 3.520, val: n/a | iter time: 56.90 ms
Epoch 1 | iter 8 step 0 | loss train: 3.578, val: n/a | iter time: 45.44 ms
Epoch 1 | iter 9 step 0 | loss train: 3.563, val: n/a | iter time: 44.71 ms
Epoch 1 | iter 10 step 0 | loss train: 3.597, val: n/a | iter time: 45.87 ms
Epoch 1 | iter 11 step 0 | loss train: 3.616, val: n/a | iter time: 46.38 ms
Epoch 1 | iter 12 step 0 | loss train: 3.616, val: n/a | iter time: 45.43 ms
Epoch 1 | iter 13 step 0 | loss train: 3.642, val: n/a | iter time: 44.54 ms
Epoch 1 | iter 14 step 0 | loss train: 3.668, val: n/a | iter time: 45.77 ms
Epoch 1 | iter 15 step 0 | loss train: 3.620, val: n/a | iter time: 60.61 ms
Epoch 1 | iter 16 step 0 | loss train: 3.628, val: n/a | iter time: 45.21 ms
Epoch 1 | iter 17 step 0 | loss train: 3.642, val: n/a | iter time: 44.68 ms
Epoch 1 | iter 18 step 0 | loss train: 3.655, val: n/a | iter time: 45.04 ms
Epoch 1 | iter 19 step 0 | loss train: 3.640, val: n/a | iter time: 49.91 ms
Epoch 1 | iter 20 step 0 | loss train: 3.640, val: n/a | iter time: 46.09 ms
Epoch 1 | iter 21 step 0 | loss train: 3.644, val: n/a | iter time: 45.44 ms
Epoch 1 | iter 22 step 0 | loss train: 3.675, val: n/a | iter time: 46.64 ms
Epoch 1 | iter 23 step 0 | loss train: 3.691, val: n/a | iter time: 46.61 ms
Epoch 1 | iter 24 step 0 | loss train: 3.683, val: n/a | iter time: 45.79 ms
Epoch 1 | iter 25 step 0 | loss train: 3.711, val: n/a | iter time: 44.74 ms
Epoch 1 | iter 26 step 0 | loss train: 3.712, val: n/a | iter time: 45.42 ms
Epoch 1 | iter 27 step 0 | loss train: 3.703, val: n/a | iter time: 47.60 ms
Epoch 1 | iter 28 step 0 | loss train: 3.717, val: n/a | iter time: 44.64 ms
Epoch 1 | iter 29 step 0 | loss train: 3.698, val: n/a | iter time: 45.45 ms
Epoch 1 | iter 30 step 0 | loss train: 3.698, val: n/a | iter time: 45.57 ms
Epoch 1 | iter 31 step 0 | loss train: 3.701, val: n/a | iter time: 41.78 ms
Epoch 1 | iter 32 step 1 | loss train: 3.694, val: n/a | iter time: 88.82 ms (step)
Epoch 1 | iter 33 step 1 | loss train: 3.693, val: n/a | iter time: 46.71 ms
Epoch 1 | iter 34 step 1 | loss train: 3.713, val: n/a | iter time: 45.51 ms
Epoch 1 | iter 35 step 1 | loss train: 3.726, val: n/a | iter time: 46.02 ms
Epoch 1 | iter 36 step 1 | loss train: 3.702, val: n/a | iter time: 47.01 ms
Epoch 1 | iter 37 step 1 | loss train: 3.697, val: n/a | iter time: 47.23 ms
Epoch 1 | iter 38 step 1 | loss train: 3.685, val: n/a | iter time: 41.38 ms
Epoch 1 | iter 39 step 1 | loss train: 3.704, val: n/a | iter time: 47.50 ms
Epoch 1 | iter 40 step 1 | loss train: 3.694, val: n/a | iter time: 45.70 ms
Epoch 1 | iter 41 step 1 | loss train: 3.701, val: n/a | iter time: 46.22 ms
Epoch 1 | iter 42 step 1 | loss train: 3.709, val: n/a | iter time: 44.80 ms
Epoch 1 | iter 43 step 1 | loss train: 3.721, val: n/a | iter time: 40.61 ms
Epoch 1 | iter 44 step 1 | loss train: 3.751, val: n/a | iter time: 46.09 ms
Epoch 1 | iter 45 step 1 | loss train: 3.735, val: n/a | iter time: 41.16 ms
Epoch 1 | iter 46 step 1 | loss train: 3.724, val: n/a | iter time: 45.73 ms
Epoch 1 | iter 47 step 1 | loss train: 3.737, val: n/a | iter time: 45.53 ms
Epoch 1 | iter 48 step 1 | loss train: 3.730, val: n/a | iter time: 47.63 ms
Epoch 1 | iter 49 step 1 | loss train: 3.728, val: n/a | iter time: 40.06 ms
Epoch 1 | iter 50 step 1 | loss train: 3.731, val: n/a | iter time: 46.00 ms
Epoch 1 | iter 51 step 1 | loss train: 3.735, val: n/a | iter time: 46.68 ms
Epoch 1 | iter 52 step 1 | loss train: 3.725, val: n/a | iter time: 46.98 ms
Epoch 1 | iter 53 step 1 | loss train: 3.710, val: n/a | iter time: 48.80 ms
Epoch 1 | iter 54 step 1 | loss train: 3.689, val: n/a | iter time: 51.27 ms
Epoch 1 | iter 55 step 1 | loss train: 3.678, val: n/a | iter time: 44.78 ms
Epoch 1 | iter 56 step 1 | loss train: 3.683, val: n/a | iter time: 46.56 ms
Epoch 1 | iter 57 step 1 | loss train: 3.665, val: n/a | iter time: 46.47 ms
Epoch 1 | iter 58 step 1 | loss train: 3.659, val: n/a | iter time: 40.90 ms
Epoch 1 | iter 59 step 1 | loss train: 3.670, val: n/a | iter time: 40.02 ms
Epoch 1 | iter 60 step 1 | loss train: 3.656, val: n/a | iter time: 48.79 ms
Epoch 1 | iter 61 step 1 | loss train: 3.670, val: n/a | iter time: 39.92 ms
Epoch 1 | iter 62 step 1 | loss train: 3.669, val: n/a | iter time: 40.78 ms
Epoch 1 | iter 63 step 1 | loss train: 3.652, val: n/a | iter time: 47.61 ms
Epoch 1 | iter 64 step 2 | loss train: 3.648, val: n/a | iter time: 43.19 ms (step)
Epoch 1 | iter 65 step 2 | loss train: 3.633, val: n/a | iter time: 47.69 ms
Epoch 1 | iter 66 step 2 | loss train: 3.629, val: n/a | iter time: 45.64 ms
Epoch 1 | iter 67 step 2 | loss train: 3.609, val: n/a | iter time: 47.17 ms
Epoch 1 | iter 68 step 2 | loss train: 3.633, val: n/a | iter time: 45.16 ms
Epoch 1 | iter 69 step 2 | loss train: 3.632, val: n/a | iter time: 48.77 ms
Epoch 1 | iter 70 step 2 | loss train: 3.642, val: n/a | iter time: 40.05 ms
Epoch 1 | iter 71 step 2 | loss train: 3.640, val: n/a | iter time: 46.06 ms
Epoch 1 | iter 72 step 2 | loss train: 3.641, val: n/a | iter time: 47.58 ms
Epoch 1 | iter 73 step 2 | loss train: 3.639, val: n/a | iter time: 40.69 ms
Epoch 1 | iter 74 step 2 | loss train: 3.621, val: n/a | iter time: 47.92 ms
Epoch 1 | iter 75 step 2 | loss train: 3.615, val: n/a | iter time: 46.60 ms
Epoch 1 | iter 76 step 2 | loss train: 3.604, val: n/a | iter time: 44.83 ms
Epoch 1 | iter 77 step 2 | loss train: 3.606, val: n/a | iter time: 40.54 ms
Epoch 1 | iter 78 step 2 | loss train: 3.606, val: n/a | iter time: 40.81 ms
Epoch 1 | iter 79 step 2 | loss train: 3.608, val: n/a | iter time: 46.99 ms
Epoch 1 | iter 80 step 2 | loss train: 3.596, val: n/a | iter time: 58.84 ms
Epoch 1 | iter 81 step 2 | loss train: 3.588, val: n/a | iter time: 49.23 ms
Epoch 1 | iter 82 step 2 | loss train: 3.582, val: n/a | iter time: 41.75 ms
Epoch 1 | iter 83 step 2 | loss train: 3.591, val: n/a | iter time: 46.54 ms
Epoch 1 | iter 84 step 2 | loss train: 3.601, val: n/a | iter time: 45.42 ms
Epoch 1 | iter 85 step 2 | loss train: 3.624, val: n/a | iter time: 46.42 ms
Epoch 1 | iter 86 step 2 | loss train: 3.628, val: n/a | iter time: 43.81 ms
Epoch 1 | iter 87 step 2 | loss train: 3.617, val: n/a | iter time: 42.21 ms
Epoch 1 | iter 88 step 2 | loss train: 3.619, val: n/a | iter time: 45.45 ms
Epoch 1 | iter 89 step 2 | loss train: 3.611, val: n/a | iter time: 41.61 ms
Epoch 1 | iter 90 step 2 | loss train: 3.607, val: n/a | iter time: 46.45 ms
Epoch 1 | iter 91 step 2 | loss train: 3.584, val: n/a | iter time: 46.47 ms
Epoch 1 | iter 92 step 2 | loss train: 3.580, val: n/a | iter time: 45.49 ms
Epoch 1 | iter 93 step 2 | loss train: 3.582, val: n/a | iter time: 46.48 ms
Epoch 1 | iter 94 step 2 | loss train: 3.577, val: n/a | iter time: 48.91 ms
Epoch 1 | iter 95 step 2 | loss train: 3.591, val: n/a | iter time: 41.85 ms
Epoch 1 | iter 96 step 3 | loss train: 3.593, val: n/a | iter time: 48.97 ms (step)
Epoch 1 | iter 97 step 3 | loss train: 3.610, val: n/a | iter time: 46.24 ms
Epoch 1 | iter 98 step 3 | loss train: 3.613, val: n/a | iter time: 39.76 ms
Epoch 1 | iter 99 step 3 | loss train: 3.617, val: n/a | iter time: 41.80 ms
Epoch 1 | iter 100 step 3 | loss train: 3.607, val: n/a | iter time: 41.20 ms
Epoch 1 | iter 101 step 3 | loss train: 3.621, val: n/a | iter time: 41.01 ms
Epoch 1 | iter 102 step 3 | loss train: 3.608, val: n/a | iter time: 41.32 ms
Epoch 1 | iter 103 step 3 | loss train: 3.607, val: n/a | iter time: 46.45 ms
Epoch 1 | iter 104 step 3 | loss train: 3.611, val: n/a | iter time: 41.26 ms
Epoch 1 | iter 105 step 3 | loss train: 3.594, val: n/a | iter time: 46.21 ms
Epoch 1 | iter 106 step 3 | loss train: 3.594, val: n/a | iter time: 46.29 ms
Epoch 1 | iter 107 step 3 | loss train: 3.572, val: n/a | iter time: 41.89 ms
Epoch 1 | iter 108 step 3 | loss train: 3.564, val: n/a | iter time: 47.57 ms
Epoch 1 | iter 109 step 3 | loss train: 3.558, val: n/a | iter time: 48.53 ms
Epoch 1 | iter 110 step 3 | loss train: 3.562, val: n/a | iter time: 41.53 ms
Epoch 1 | iter 111 step 3 | loss train: 3.569, val: n/a | iter time: 40.30 ms
Epoch 1 | iter 112 step 3 | loss train: 3.593, val: n/a | iter time: 45.65 ms
Epoch 1 | iter 113 step 3 | loss train: 3.587, val: n/a | iter time: 48.54 ms
Epoch 1 | iter 114 step 3 | loss train: 3.582, val: n/a | iter time: 46.24 ms
Epoch 1 | iter 115 step 3 | loss train: 3.587, val: n/a | iter time: 41.55 ms
Epoch 1 | iter 116 step 3 | loss train: 3.584, val: n/a | iter time: 46.67 ms
Epoch 1 | iter 117 step 3 | loss train: 3.578, val: n/a | iter time: 40.28 ms
Epoch 1 | iter 118 step 3 | loss train: 3.567, val: n/a | iter time: 47.60 ms
Epoch 1 | iter 119 step 3 | loss train: 3.585, val: n/a | iter time: 45.40 ms
Epoch 1 | iter 120 step 3 | loss train: 3.592, val: n/a | iter time: 40.08 ms
Epoch 1 | iter 121 step 3 | loss train: 3.600, val: n/a | iter time: 41.40 ms
Epoch 1 | iter 122 step 3 | loss train: 3.614, val: n/a | iter time: 45.83 ms
Epoch 1 | iter 123 step 3 | loss train: 3.638, val: n/a | iter time: 46.04 ms
Epoch 1 | iter 124 step 3 | loss train: 3.649, val: n/a | iter time: 47.09 ms
Epoch 1 | iter 125 step 3 | loss train: 3.653, val: n/a | iter time: 41.23 ms
Epoch 1 | iter 126 step 3 | loss train: 3.658, val: n/a | iter time: 41.12 ms
Epoch 1 | iter 127 step 3 | loss train: 3.662, val: n/a | iter time: 39.89 ms
Epoch 1 | iter 128 step 4 | loss train: 3.676, val: n/a | iter time: 41.69 ms (step)
Epoch 1 | iter 129 step 4 | loss train: 3.673, val: n/a | iter time: 47.26 ms
Epoch 1 | iter 130 step 4 | loss train: 3.669, val: n/a | iter time: 47.70 ms
Epoch 1 | iter 131 step 4 | loss train: 3.692, val: n/a | iter time: 47.40 ms
Epoch 1 | iter 132 step 4 | loss train: 3.692, val: n/a | iter time: 47.56 ms
Epoch 1 | iter 133 step 4 | loss train: 3.691, val: n/a | iter time: 41.75 ms
Epoch 1 | iter 134 step 4 | loss train: 3.705, val: n/a | iter time: 40.49 ms
Epoch 1 | iter 135 step 4 | loss train: 3.710, val: n/a | iter time: 41.52 ms
Epoch 1 | iter 136 step 4 | loss train: 3.697, val: n/a | iter time: 48.29 ms
Epoch 1 | iter 137 step 4 | loss train: 3.731, val: n/a | iter time: 47.32 ms
Epoch 1 | iter 138 step 4 | loss train: 3.731, val: n/a | iter time: 41.67 ms
Epoch 1 | iter 139 step 4 | loss train: 3.739, val: n/a | iter time: 42.56 ms
Epoch 1 | iter 140 step 4 | loss train: 3.725, val: n/a | iter time: 41.43 ms
Epoch 1 | iter 141 step 4 | loss train: 3.729, val: n/a | iter time: 47.89 ms
Epoch 1 | iter 142 step 4 | loss train: 3.741, val: n/a | iter time: 40.41 ms
Epoch 1 | iter 143 step 4 | loss train: 3.751, val: n/a | iter time: 41.44 ms
Epoch 1 | iter 144 step 4 | loss train: 3.752, val: n/a | iter time: 47.36 ms
Epoch 1 | iter 145 step 4 | loss train: 3.753, val: n/a | iter time: 41.86 ms
Epoch 1 | iter 146 step 4 | loss train: 3.754, val: n/a | iter time: 42.43 ms
Epoch 1 | iter 147 step 4 | loss train: 3.739, val: n/a | iter time: 61.65 ms
Epoch 1 | iter 148 step 4 | loss train: 3.741, val: n/a | iter time: 49.00 ms
Epoch 1 | iter 149 step 4 | loss train: 3.735, val: n/a | iter time: 47.85 ms
Epoch 1 | iter 150 step 4 | loss train: 3.739, val: n/a | iter time: 42.17 ms
Epoch 1 | iter 151 step 4 | loss train: 3.723, val: n/a | iter time: 42.81 ms
Epoch 1 | iter 152 step 4 | loss train: 3.716, val: n/a | iter time: 47.36 ms
Epoch 1 | iter 153 step 4 | loss train: 3.696, val: n/a | iter time: 42.37 ms
Epoch 1 | iter 154 step 4 | loss train: 3.697, val: n/a | iter time: 46.37 ms
Epoch 1 | iter 155 step 4 | loss train: 3.679, val: n/a | iter time: 47.88 ms
Epoch 1 | iter 156 step 4 | loss train: 3.670, val: n/a | iter time: 44.31 ms
Epoch 1 | iter 157 step 4 | loss train: 3.655, val: n/a | iter time: 41.51 ms
Epoch 1 | iter 158 step 4 | loss train: 3.668, val: n/a | iter time: 40.75 ms
Epoch 1 | iter 159 step 4 | loss train: 3.651, val: n/a | iter time: 50.43 ms
Epoch 1 | iter 160 step 5 | loss train: 3.654, val: n/a | iter time: 41.11 ms (step)
Training time: 29.00s
Memory used: 2.60 GB
Saving LoRA weights to 'out/finetune/lora/final/lit_model.pth.lora'
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/bin/litgpt", line 8, in <module>
    sys.exit(main())
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/litgpt/__main__.py", line 129, in main
    fn(**kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/litgpt/finetune/lora.py", line 140, in setup
    fabric.launch(main, devices, seed, config, data, checkpoint_dir, out_dir, train, eval)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 866, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 952, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 957, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/litgpt/finetune/lora.py", line 220, in main
    merge_lora(checkpoint_dir=save_path.parent)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/litgpt/scripts/merge_lora.py", line 56, in merge_lora
    merge_lora_weights(model)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/litgpt/lora.py", line 746, in merge_lora_weights
    module.merge()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/litgpt/lora.py", line 400, in merge
    super().merge()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/litgpt/lora.py", line 164, in merge
    raise NotImplementedError(
NotImplementedError: Cannot merge the pretrained weights of type torch.float16 and LoRA weights of type torch.float32
```

**Comment by rasbt** [comment]
Works fine with other models like TinyLlama. I believe that's due to the default precision in Pythia models. Still something we should address.

**Comment by carmocca** [comment]
Why are the LoRA weights in fp32? Seems like a bug

**Comment by AdrianVispalia** [comment]
This is my current workaround:

```bash
litgpt finetune lora \
  --checkpoint_dir checkpoints/EleutherAI/pythia-1b \
  --data Alpaca \
  --out_dir out/pythia-1b-lora \
  --precision "16-mixed"
```

**Comment by carmocca** [comment]
Fixed

**Comment by AdrianVispalia** [comment]
> Fixed

After testing it with the fix, I still have an issue merging on 1 of my 2 hardware setups.

Information:
- Pythia-1b with LoRa finetuning
- 2x NVIDIA A100-PCIE-40GB, AMD EPYC 7313, 256 GB RAM


Results:
- If precision is not set or set to 16-mixed or 32-true I get an error due to different dtypes (NotImplementedError: Cannot merge the pretrained weights of type torch.float16 and LoRA weights of type torch.float32)
- if precision is 16-true, a different error is raised (RuntimeError: probability tensor contains either inf, nan or element < 0)

Would it be troublesome to add on https://github.com/Lightning-AI/litgpt/blob/main/litgpt/lora.py#L163 a lossy cast implementation (maybe also outputting a warning about it)? Like:

```python
elif torch.finfo(pretrained_dtype).max >= torch.finfo(lora_data.dtype).max:
    # ...
else:
    available_dtypes = [torch.float16, torch.float32]
    if pretrained_dtype in available_dtypes and lora_data.dtype in available_dtypes:
        transformed_lora_data = lora_data.to(
            device=self.linear.weight.data.device,
            dtype=pretrained_dtype
        )
        self.linear.weight.data += transformed_lora_data
    else:
        raise NotImplementedError(
            f"Cannot merge the pretrained weights of type {pretrained_dtype}"
            f" and LoRA weights of type {lora_data.dtype}"
        )
```

**Comment by carmocca** [comment]
Hey Adrian. In https://github.com/Lightning-AI/litgpt/pull/1248 I'm proposing that we simply let pytorch do its pytorch thing
